-- Immutable PostgreSQL fixture representing the collaboration schema before issue #265.

create table workflow_collaboration_session (
    session_id varchar(255) not null,
    lock_version bigint not null,
    collaboration_mode varchar(64) not null,
    owner_actor_id varchar(255) not null,
    owner_user_id varchar(255) not null,
    owner_display_name varchar(1024) not null,
    created_at timestamp(6) with time zone not null,
    workflow_id varchar(255) not null,
    workflow_dsl oid not null,
    semantic_revision bigint not null,
    event_sequence bigint not null,
    session_closed boolean not null,
    primary key (session_id)
);

create index idx_workflow_session_open
    on workflow_collaboration_session (session_closed);
create index idx_workflow_session_workflow
    on workflow_collaboration_session (workflow_id);

create table workflow_collaboration_operation (
    id bigint generated by default as identity not null,
    session_id varchar(255) not null,
    operation_id varchar(255) not null,
    actor_id varchar(255) not null,
    operation_type varchar(255) not null,
    occurred_at timestamp(6) with time zone not null,
    operation_sequence bigint not null,
    semantic_revision bigint not null,
    operation_payload oid not null,
    primary key (id),
    constraint uk_workflow_operation_id unique (operation_id),
    constraint uk_workflow_operation_sequence unique (session_id, operation_sequence)
);

create index idx_workflow_operation_session
    on workflow_collaboration_operation (session_id);
create index idx_workflow_operation_revision
    on workflow_collaboration_operation (session_id, semantic_revision);

create table workflow_collaboration_outbox (
    event_id varchar(255) not null,
    session_id varchar(255) not null,
    event_sequence bigint not null,
    semantic_revision bigint not null,
    event_type varchar(255) not null,
    occurred_at timestamp(6) with time zone not null,
    event_payload oid not null,
    attempt_count integer not null,
    next_attempt_at timestamp(6) with time zone not null,
    published_at timestamp(6) with time zone,
    primary key (event_id),
    constraint uk_workflow_outbox_sequence unique (session_id, event_sequence)
);

create index idx_workflow_outbox_pending
    on workflow_collaboration_outbox (published_at, next_attempt_at);
create index idx_workflow_outbox_session
    on workflow_collaboration_outbox (session_id);

insert into workflow_collaboration_session (
    session_id,
    lock_version,
    collaboration_mode,
    owner_actor_id,
    owner_user_id,
    owner_display_name,
    created_at,
    workflow_id,
    workflow_dsl,
    semantic_revision,
    event_sequence,
    session_closed
) values (
    'legacy.session',
    0,
    'SHARED_SESSION_PERSONAL_UNDO',
    'legacy.actor',
    'legacy.user',
    'Legacy User',
    '2026-07-18T02:00:00Z',
    'legacy.workflow',
    lo_from_bytea(0, convert_to('legacy-workflow-dsl', 'UTF8')),
    1,
    2,
    false
);

insert into workflow_collaboration_operation (
    id,
    session_id,
    operation_id,
    actor_id,
    operation_type,
    occurred_at,
    operation_sequence,
    semantic_revision,
    operation_payload
) values (
    1,
    'legacy.session',
    'legacy.operation',
    'legacy.actor',
    'CreateNode',
    '2026-07-18T02:00:01Z',
    1,
    1,
    lo_from_bytea(0, convert_to('legacy-operation-payload', 'UTF8'))
);

insert into workflow_collaboration_outbox (
    event_id,
    session_id,
    event_sequence,
    semantic_revision,
    event_type,
    occurred_at,
    event_payload,
    attempt_count,
    next_attempt_at,
    published_at
) values (
    'legacy.event.pending',
    'legacy.session',
    1,
    1,
    'WORKFLOW_OPERATION_ACCEPTED',
    '2026-07-18T02:00:01Z',
    lo_from_bytea(0, convert_to('legacy-pending-event-payload', 'UTF8')),
    2,
    '2026-07-18T02:05:00Z',
    null
);

insert into workflow_collaboration_outbox (
    event_id,
    session_id,
    event_sequence,
    semantic_revision,
    event_type,
    occurred_at,
    event_payload,
    attempt_count,
    next_attempt_at,
    published_at
) values (
    'legacy.event.published',
    'legacy.session',
    2,
    1,
    'WORKFLOW_SESSION_SNAPSHOT',
    '2026-07-18T02:00:02Z',
    lo_from_bytea(0, convert_to('legacy-published-event-payload', 'UTF8')),
    1,
    '2026-07-18T02:00:02Z',
    '2026-07-18T02:00:03Z'
);
