-- Audio Analyzer-owned collaboration schema before leased outbox dispatch.

create table workflow_collaboration_session (
    session_id varchar(255) not null,
    lock_version bigint not null,
    collaboration_mode varchar(64) not null,
    owner_actor_id varchar(255) not null,
    owner_user_id varchar(255) not null,
    owner_display_name varchar(1024) not null,
    created_at timestamp(6) with time zone not null,
    workflow_id varchar(255) not null,
    workflow_dsl clob not null,
    semantic_revision bigint not null,
    event_sequence bigint not null,
    session_closed boolean not null,
    primary key (session_id)
);

create index idx_workflow_session_open
    on workflow_collaboration_session (session_closed);
create index idx_workflow_session_workflow
    on workflow_collaboration_session (workflow_id);

create table workflow_collaboration_operation (
    id bigint generated by default as identity not null,
    session_id varchar(255) not null,
    operation_id varchar(255) not null,
    actor_id varchar(255) not null,
    operation_type varchar(255) not null,
    occurred_at timestamp(6) with time zone not null,
    operation_sequence bigint not null,
    semantic_revision bigint not null,
    operation_payload clob not null,
    primary key (id),
    constraint uk_workflow_operation_id unique (operation_id),
    constraint uk_workflow_operation_sequence unique (session_id, operation_sequence)
);

create index idx_workflow_operation_session
    on workflow_collaboration_operation (session_id);
create index idx_workflow_operation_revision
    on workflow_collaboration_operation (session_id, semantic_revision);

create table workflow_collaboration_outbox (
    event_id varchar(255) not null,
    session_id varchar(255) not null,
    event_sequence bigint not null,
    semantic_revision bigint not null,
    event_type varchar(255) not null,
    occurred_at timestamp(6) with time zone not null,
    event_payload clob not null,
    attempt_count integer not null,
    next_attempt_at timestamp(6) with time zone not null,
    published_at timestamp(6) with time zone,
    primary key (event_id),
    constraint uk_workflow_outbox_sequence unique (session_id, event_sequence)
);

create index idx_workflow_outbox_pending
    on workflow_collaboration_outbox (published_at, next_attempt_at);
create index idx_workflow_outbox_session
    on workflow_collaboration_outbox (session_id);
