-- Audio Analyzer-owned, rebuildable branch-aware workflow semantic projection.

create table workflow_semantic_index (
    id bigint generated by default as identity not null,
    repository_name varchar(255) not null,
    branch_name varchar(255) not null,
    object_id varchar(40) not null,
    branch_position integer not null,
    workflow_id varchar(255) not null,
    workflow_name varchar(2048) not null,
    node_ids varchar(65535) not null,
    node_types varchar(65535) not null,
    node_labels varchar(65535) not null,
    node_label_text varchar(65535) not null,
    property_keys varchar(65535) not null,
    property_values varchar(65535) not null,
    property_pairs varchar(65535) not null,
    primary key (id),
    constraint uk_workflow_semantic_repo_branch_commit
        unique (repository_name, branch_name, object_id)
);

create index idx_workflow_semantic_repo_branch_position
    on workflow_semantic_index (repository_name, branch_name, branch_position);
create index idx_workflow_semantic_repo_workflow
    on workflow_semantic_index (repository_name, workflow_id);
